FROM ubuntu:24.04
ARG DEBIAN_FRONTEND=noninteractive

WORKDIR /tmp

# Prerequisites
RUN apt-get update \
  && apt-get install \
       build-essential software-properties-common apt-transport-https lsb-release ca-certificates \
       sudo git make cmake wget curl lsof unzip \
       python3 python3-pip -y 

RUN pip install torch transformers ultralytics python-opencv huggingface_hub